# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  current_dir = `pwd`.strip

  puts "fourseasons vagrant"
  config.vm.provision :shell, :path => "vagrant_startup.sh"
  config.vm.network :hostonly, "172.16.1.17"
  config.vm.share_folder("working", "/working", ".", :nfs => false)

  config.vm.provision :shell, :path => "vagrant_startup.sh"

  config.vm.customize ["modifyvm", :id, "--memory", "1200"]
  config.vm.customize ["modifyvm", :id, "--cpus", "4"]

end
